---
## File: services.yml - services configuration

- name: Configure consul services
  ansible.builtin.template:
    dest: "{{ consul_configd_path }}/service_{{ service_item.id }}.json"
    src: service.json.j2
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0644"
  with_items: "{{ consul_services }}"
  loop_control:
    loop_var: service_item
  notify:
    - restart consul

- name: Set fact with list of existing configuration files
  ansible.builtin.set_fact:
    list_current_service_config: "{{ list_current_service_config | default([]) + [config_file_item.path] }}"
  with_items: "{{ services_enabled_files }}"
  loop_control:
    loop_var: config_file_item
