- name: remove_cluster.yml | Remove PostgreSQL HA Cluster
  hosts: postgres_cluster
  become: true
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
  tasks:
    - block:
        - name: Stop Patroni service
          ansible.builtin.service:
            name: patroni
            state: stopped
            enabled: false

        - name: Delete PostgreSQL database content
          ansible.builtin.file:
            path: "{{ postgresql_data_dir }}"
            state: absent
      when: remove_postgres | default(false) | bool

- name: remove_cluster.yml | Etcd Cluster Play
  hosts: etcd_cluster
  become: true
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
  tasks:
    - block:
        - name: Stop Etcd service
          ansible.builtin.service:
            name: etcd
            state: stopped
            enabled: false

        - name: Delete Etcd content
          ansible.builtin.file:
            path: "{{ etcd_data_dir }}/member"
            state: absent
      when: remove_etcd | default(false) | bool
