---
# Extension Auto-Setup: repository

# TimescaleDB (if 'enable_timescale' is 'true')
- block:
    # Debian based
    - name: Add TimescaleDB repository
      ansible.builtin.apt_repository:
        repo: "deb https://packagecloud.io/timescale/timescaledb/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
        state: present
        filename: "timescaledb"
        key: "https://packagecloud.io/timescale/timescaledb/gpgkey"
      when: ansible_os_family == "Debian"

    # RedHat based
    - name: Add TimescaleDB repository
      ansible.builtin.yum_repository:
        name: "timescaledb"
        description: "TimescaleDB Repository"
        baseurl: "https://packagecloud.io/timescale/timescaledb/el/{{ ansible_distribution_major_version }}/x86_64"
        gpgkey: "https://packagecloud.io/timescale/timescaledb/gpgkey"
        gpgcheck: "no"
      when: ansible_os_family == "RedHat"
  environment: "{{ proxy_env | default({}) }}"
  when: (enable_timescale | default(false) | bool) or (enable_timescaledb | default(false) | bool)
  tags: add_repo, timescaledb, timescale


- block:
    # Debian based
    - name: Add Citus repository
      ansible.builtin.apt_repository:
        repo: "deb https://repos.citusdata.com/community/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"
        state: present
        filename: "citusdata"
        key: "https://repos.citusdata.com/community/gpgkey"
      when: ansible_os_family == "Debian"

    # RedHat based
    # TODO: Tests have shown that distributions such as Rocky Linux, AlmaLinux, Oracle Linux, and CentOS Stream are not yet supported.
#    - name: Add Citus repository
#      ansible.builtin.yum_repository:
#        name: "citusdata"
#        description: "Citus Repository"
#        baseurl: "https://repos.citusdata.com/community/yum/{{ ansible_distribution_major_version }}/x86_64"
#        gpgkey: "https://repos.citusdata.com/community/gpgkey"
#        gpgcheck: "no"
#      when: ansible_os_family == "RedHat"
  environment: "{{ proxy_env | default({}) }}"
  when:
    - enable_citus | default(false) | bool
    - postgresql_version | int >= 11
  tags: add_repo, citus


...
