---

- block:  # Debian/Ubuntu
    - name: Add repository apt-key
      ansible.builtin.apt_key:
        url: "{{ item.key }}"
        state: present
      loop: "{{ apt_repository_keys }}"
      when: apt_repository_keys | length > 0

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        state: present
        update_cache: true
      loop: "{{ apt_repository }}"
      when: apt_repository | length > 0
  environment: "{{ proxy_env | default({}) }}"
  when: installation_method == "repo" and ansible_os_family == "Debian"
  tags: add_repo

...
